# Generated by Django 6.0.4 on 2026-07-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_portalactivationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalactivationotp',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Activation'), ('password_reset', 'Password Reset')], default='activation', max_length=30),
        ),
    ]
