# Generated by Django 6.0.4 on 2026-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_created_by_client_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pppoe_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
