# Generated by Django 6.0.4 on 2026-05-17 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_pppoe_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pppoe_username', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('activated', 'Activated'), ('disconnected', 'Disconnected')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
