# Generated by Django 6.0.4 on 2026-05-21 02:30

from django.db import migrations, models
from django.db.models import Q


def generate_unique_account_numbers(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    existing_numbers = set(
        Client.objects.exclude(account_number__isnull=True)
        .exclude(account_number='')
        .values_list('account_number', flat=True)
    )

    for client in Client.objects.filter(Q(account_number__isnull=True) | Q(account_number='')):
        number = f"NXV-{client.pk:06d}"
        if number in existing_numbers:
            counter = 1
            while True:
                candidate = f"NXV-{client.pk:06d}-{counter}"
                if candidate not in existing_numbers:
                    number = candidate
                    break
                counter += 1
        existing_numbers.add(number)
        client.account_number = number
        client.save(update_fields=['account_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(generate_unique_account_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
