# Generated by Django 6.0.4 on 2026-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pppoe_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
