# Generated by Django 6.0.4 on 2026-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_client_email_alter_client_pppoe_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
