# Generated by Django 6.0.4 on 2026-05-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_client_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('underpaid', 'Underpaid'), ('credit', 'Credit')], default='pending', max_length=20),
        ),
    ]
