# Generated by Django 6.0.4 on 2026-06-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
