# Generated by Django 6.0.4 on 2026-06-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_invoice_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
