# Generated by Django 6.0.4 on 2026-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='gateway_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
