# Generated by Django 6.0.4 on 2026-06-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_notificationlog_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='gateway_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
