# Generated by Django 6.0.4 on 2026-06-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_notificationlog_gateway_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('expiring', 'Expiring'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('payment_confirmation', 'Payment Confirmation')], max_length=20),
        ),
    ]
