# Generated by Django 6.0.4 on 2026-06-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_payment_account_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
