# Generated by Django 6.0.4 on 2026-06-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='callback_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
