# Generated by Django 6.0.4 on 2026-06-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_mpesatransaction_callback_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
