# Generated by Django 6.0.4 on 2026-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_mpesatransaction_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StkPushRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=255, unique=True)),
                ('checkout_request_id', models.CharField(max_length=255, unique=True)),
                ('account_reference', models.CharField(db_index=True, max_length=20)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_description', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'STK Push Request',
                'verbose_name_plural': 'STK Push Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
