# Generated by Django 6.0.4 on 2026-08-16 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_extensionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Extension Log', 'verbose_name_plural': 'Extension Logs'},
        ),
        migrations.AlterField(
            model_name='extensionlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_logs', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='extensionlog',
            name='days_added',
            field=models.PositiveIntegerField(help_text='Number of days added to the subscription.'),
        ),
        migrations.AlterField(
            model_name='extensionlog',
            name='new_end_date',
            field=models.DateField(help_text='New expiry date after the extension was applied.'),
        ),
        migrations.AlterField(
            model_name='extensionlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who performed the extension.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extensionlog',
            name='previous_end_date',
            field=models.DateField(blank=True, help_text='Expiry date before the extension was applied.', null=True),
        ),
        migrations.AlterField(
            model_name='extensionlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the extension.', null=True),
        ),
        migrations.AlterField(
            model_name='extensionlog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_logs', to='clients.subscription'),
        ),
    ]
