# Generated by Django 6.0.4 on 2026-08-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_alter_extensionlog_options_alter_extensionlog_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if this allocation was reversed/unallocated.')),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, help_text='Reason for unallocation or payment refund.', null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='clients.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='clients.payment')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'ordering': ['-allocated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_allocation_amount_positive')],
            },
        ),
    ]
