# Generated by Django 6.0.4 on 2026-08-31 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_paymentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('equipment', 'Equipment'), ('service', 'Service'), ('other', 'Other')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='renewal_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this subscription invoice triggered a renewal.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.subscription'),
        ),
        migrations.AlterField(
            model_name='mikrotiklog',
            name='action',
            field=models.CharField(choices=[('activated', 'Activated'), ('disconnected', 'Disconnected'), ('error', 'Error')], max_length=20),
        ),
    ]
