# Generated by Django 6.0.4 on 2026-09-02 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_invoice_invoice_type_invoice_renewal_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_allocations', to='clients.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_allocations', to='clients.invoice')),
            ],
        ),
    ]
