# Generated by Django 6.0.4 on 2026-09-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_walletallocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletallocation',
            options={'ordering': ['-allocated_at'], 'verbose_name': 'Wallet Allocation', 'verbose_name_plural': 'Wallet Allocations'},
        ),
        migrations.AddField(
            model_name='walletallocation',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this wallet allocation was reversed.'),
        ),
        migrations.AddField(
            model_name='walletallocation',
            name='reversal_reason',
            field=models.TextField(blank=True, help_text='Reason for reversing this wallet allocation.', null=True),
        ),
        migrations.AddField(
            model_name='walletallocation',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='walletallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_allocation_amount_positive'),
        ),
    ]
