# Generated by Django 6.0.4 on 2026-09-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotspot Location',
                'verbose_name_plural': 'Hotspot Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotspotPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Maximum duration of the plan in minutes.', null=True)),
                ('data_limit_mb', models.PositiveIntegerField(blank=True, help_text='Maximum data allowance in MB.', null=True)),
                ('download_speed_kbps', models.PositiveIntegerField(blank=True, help_text='Download speed limit in Kbps.', null=True)),
                ('upload_speed_kbps', models.PositiveIntegerField(blank=True, help_text='Upload speed limit in Kbps.', null=True)),
                ('simultaneous_devices', models.PositiveIntegerField(default=1, help_text='Maximum number of devices allowed at the same time.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotspot Plan',
                'verbose_name_plural': 'Hotspot Plans',
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotspotVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='generated', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('bound_mac', models.CharField(blank=True, help_text='Optional device MAC address bound to the voucher.', max_length=17, null=True)),
                ('data_used_mb', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='hotspot.hotspotplan')),
            ],
            options={
                'verbose_name': 'Hotspot Voucher',
                'verbose_name_plural': 'Hotspot Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotspotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='hotspot.hotspotlocation')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='hotspot.hotspotvoucher')),
            ],
            options={
                'verbose_name': 'Hotspot Session',
                'verbose_name_plural': 'Hotspot Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HotspotPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='hotspot.hotspotplan')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='hotspot.hotspotvoucher')),
            ],
            options={
                'verbose_name': 'Hotspot Purchase',
                'verbose_name_plural': 'Hotspot Purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
