# Generated by Django 6.0.4 on 2026-09-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotvoucher',
            name='activated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='hotspotvoucher',
            name='bound_mac',
            field=models.CharField(blank=True, editable=False, help_text='Device MAC address permanently bound while the voucher is active.', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='hotspotvoucher',
            name='code',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hotspotvoucher',
            name='data_used_mb',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='hotspotvoucher',
            name='expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='hotspotvoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('status', 'generated'), ('expires_at__isnull', True)), models.Q(('activated_at__isnull', False), ('expires_at__isnull', False), ('status__in', ['active', 'expired'])), ('status', 'disabled'), _connector='OR'), name='hotspot_voucher_valid_activation_state'),
        ),
    ]
