# Generated by Django 6.0.4 on 2026-09-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0002_alter_hotspotvoucher_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotpurchase',
            name='payment_reference',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
